/*
 * Seel API
 * Seel API
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Address
 */
public class AddressTest {
    private final Address model = new Address();

    /**
     * Model tests for Address
     */
    @Test
    public void testAddress() {
        // TODO: test Address
    }

    /**
     * Test the property 'address1'
     */
    @Test
    public void address1Test() {
        // TODO: test address1
    }

    /**
     * Test the property 'address2'
     */
    @Test
    public void address2Test() {
        // TODO: test address2
    }

    /**
     * Test the property 'city'
     */
    @Test
    public void cityTest() {
        // TODO: test city
    }

    /**
     * Test the property 'state'
     */
    @Test
    public void stateTest() {
        // TODO: test state
    }

    /**
     * Test the property 'zipcode'
     */
    @Test
    public void zipcodeTest() {
        // TODO: test zipcode
    }

    /**
     * Test the property 'country'
     */
    @Test
    public void countryTest() {
        // TODO: test country
    }

}
