/*
 * Seel API
 * Seel API
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.ClaimClaimDetailsInner;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Claim
 */
public class ClaimTest {
    private final Claim model = new Claim();

    /**
     * Model tests for Claim
     */
    @Test
    public void testClaim() {
        // TODO: test Claim
    }

    /**
     * Test the property 'claimId'
     */
    @Test
    public void claimIdTest() {
        // TODO: test claimId
    }

    /**
     * Test the property 'orderId'
     */
    @Test
    public void orderIdTest() {
        // TODO: test orderId
    }

    /**
     * Test the property 'contractId'
     */
    @Test
    public void contractIdTest() {
        // TODO: test contractId
    }

    /**
     * Test the property 'payoutAmount'
     */
    @Test
    public void payoutAmountTest() {
        // TODO: test payoutAmount
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'claimType'
     */
    @Test
    public void claimTypeTest() {
        // TODO: test claimType
    }

    /**
     * Test the property 'rejectReason'
     */
    @Test
    public void rejectReasonTest() {
        // TODO: test rejectReason
    }

    /**
     * Test the property 'claimDetails'
     */
    @Test
    public void claimDetailsTest() {
        // TODO: test claimDetails
    }

    /**
     * Test the property 'updatedTs'
     */
    @Test
    public void updatedTsTest() {
        // TODO: test updatedTs
    }

    /**
     * Test the property 'createdTs'
     */
    @Test
    public void createdTsTest() {
        // TODO: test createdTs
    }

}
