/*
 * Seel API
 * Seel API
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.ContractCoveredItemsInner;
import com.konfigthis.client.model.Customer;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Contract
 */
public class ContractTest {
    private final Contract model = new Contract();

    /**
     * Model tests for Contract
     */
    @Test
    public void testContract() {
        // TODO: test Contract
    }

    /**
     * Test the property 'contractId'
     */
    @Test
    public void contractIdTest() {
        // TODO: test contractId
    }

    /**
     * Test the property 'orderId'
     */
    @Test
    public void orderIdTest() {
        // TODO: test orderId
    }

    /**
     * Test the property 'quoteId'
     */
    @Test
    public void quoteIdTest() {
        // TODO: test quoteId
    }

    /**
     * Test the property 'customer'
     */
    @Test
    public void customerTest() {
        // TODO: test customer
    }

    /**
     * Test the property 'premium'
     */
    @Test
    public void premiumTest() {
        // TODO: test premium
    }

    /**
     * Test the property 'premiumTax'
     */
    @Test
    public void premiumTaxTest() {
        // TODO: test premiumTax
    }

    /**
     * Test the property 'currency'
     */
    @Test
    public void currencyTest() {
        // TODO: test currency
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'cancelledTs'
     */
    @Test
    public void cancelledTsTest() {
        // TODO: test cancelledTs
    }

    /**
     * Test the property 'createdTs'
     */
    @Test
    public void createdTsTest() {
        // TODO: test createdTs
    }

    /**
     * Test the property 'updatedTs'
     */
    @Test
    public void updatedTsTest() {
        // TODO: test updatedTs
    }

    /**
     * Test the property 'coveredItems'
     */
    @Test
    public void coveredItemsTest() {
        // TODO: test coveredItems
    }

}
