/*
 * Seel API
 * Seel API
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for FulfillmentLineItemsInner
 */
public class FulfillmentLineItemsInnerTest {
    private final FulfillmentLineItemsInner model = new FulfillmentLineItemsInner();

    /**
     * Model tests for FulfillmentLineItemsInner
     */
    @Test
    public void testFulfillmentLineItemsInner() {
        // TODO: test FulfillmentLineItemsInner
    }

    /**
     * Test the property 'lineItemId'
     */
    @Test
    public void lineItemIdTest() {
        // TODO: test lineItemId
    }

    /**
     * Test the property 'quantity'
     */
    @Test
    public void quantityTest() {
        // TODO: test quantity
    }

}
