/*
 * Seel API
 * Seel API
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.ItemShippingOrigin;
import com.konfigthis.client.model.ProductAttributes;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Item
 */
public class ItemTest {
    private final Item model = new Item();

    /**
     * Model tests for Item
     */
    @Test
    public void testItem() {
        // TODO: test Item
    }

    /**
     * Test the property 'lineItemId'
     */
    @Test
    public void lineItemIdTest() {
        // TODO: test lineItemId
    }

    /**
     * Test the property 'productId'
     */
    @Test
    public void productIdTest() {
        // TODO: test productId
    }

    /**
     * Test the property 'productTitle'
     */
    @Test
    public void productTitleTest() {
        // TODO: test productTitle
    }

    /**
     * Test the property 'productDescription'
     */
    @Test
    public void productDescriptionTest() {
        // TODO: test productDescription
    }

    /**
     * Test the property 'variantId'
     */
    @Test
    public void variantIdTest() {
        // TODO: test variantId
    }

    /**
     * Test the property 'variantTitle'
     */
    @Test
    public void variantTitleTest() {
        // TODO: test variantTitle
    }

    /**
     * Test the property 'sku'
     */
    @Test
    public void skuTest() {
        // TODO: test sku
    }

    /**
     * Test the property 'sellerId'
     */
    @Test
    public void sellerIdTest() {
        // TODO: test sellerId
    }

    /**
     * Test the property 'sellerName'
     */
    @Test
    public void sellerNameTest() {
        // TODO: test sellerName
    }

    /**
     * Test the property 'brandName'
     */
    @Test
    public void brandNameTest() {
        // TODO: test brandName
    }

    /**
     * Test the property 'quantity'
     */
    @Test
    public void quantityTest() {
        // TODO: test quantity
    }

    /**
     * Test the property 'price'
     */
    @Test
    public void priceTest() {
        // TODO: test price
    }

    /**
     * Test the property 'allocatedDiscounts'
     */
    @Test
    public void allocatedDiscountsTest() {
        // TODO: test allocatedDiscounts
    }

    /**
     * Test the property 'salesTax'
     */
    @Test
    public void salesTaxTest() {
        // TODO: test salesTax
    }

    /**
     * Test the property 'retailPrice'
     */
    @Test
    public void retailPriceTest() {
        // TODO: test retailPrice
    }

    /**
     * Test the property 'finalPrice'
     */
    @Test
    public void finalPriceTest() {
        // TODO: test finalPrice
    }

    /**
     * Test the property 'currency'
     */
    @Test
    public void currencyTest() {
        // TODO: test currency
    }

    /**
     * Test the property 'requiresShipping'
     */
    @Test
    public void requiresShippingTest() {
        // TODO: test requiresShipping
    }

    /**
     * Test the property 'productUrl'
     */
    @Test
    public void productUrlTest() {
        // TODO: test productUrl
    }

    /**
     * Test the property 'imageUrl'
     */
    @Test
    public void imageUrlTest() {
        // TODO: test imageUrl
    }

    /**
     * Test the property 'category1'
     */
    @Test
    public void category1Test() {
        // TODO: test category1
    }

    /**
     * Test the property 'category2'
     */
    @Test
    public void category2Test() {
        // TODO: test category2
    }

    /**
     * Test the property 'category3'
     */
    @Test
    public void category3Test() {
        // TODO: test category3
    }

    /**
     * Test the property 'category4'
     */
    @Test
    public void category4Test() {
        // TODO: test category4
    }

    /**
     * Test the property 'isFinalSale'
     */
    @Test
    public void isFinalSaleTest() {
        // TODO: test isFinalSale
    }

    /**
     * Test the property 'condition'
     */
    @Test
    public void conditionTest() {
        // TODO: test condition
    }

    /**
     * Test the property 'productAttributes'
     */
    @Test
    public void productAttributesTest() {
        // TODO: test productAttributes
    }

    /**
     * Test the property 'shippingOrigin'
     */
    @Test
    public void shippingOriginTest() {
        // TODO: test shippingOrigin
    }

    /**
     * Test the property 'extraInfo'
     */
    @Test
    public void extraInfoTest() {
        // TODO: test extraInfo
    }

}
