/*
 * Seel API
 * Seel API
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.MerchantUpdateMerchantDetailsRequestSeelServicesInner;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for MerchantUpdateMerchantDetailsRequest
 */
public class MerchantUpdateMerchantDetailsRequestTest {
    private final MerchantUpdateMerchantDetailsRequest model = new MerchantUpdateMerchantDetailsRequest();

    /**
     * Model tests for MerchantUpdateMerchantDetailsRequest
     */
    @Test
    public void testMerchantUpdateMerchantDetailsRequest() {
        // TODO: test MerchantUpdateMerchantDetailsRequest
    }

    /**
     * Test the property 'shopId'
     */
    @Test
    public void shopIdTest() {
        // TODO: test shopId
    }

    /**
     * Test the property 'adminDomain'
     */
    @Test
    public void adminDomainTest() {
        // TODO: test adminDomain
    }

    /**
     * Test the property 'shopDomain'
     */
    @Test
    public void shopDomainTest() {
        // TODO: test shopDomain
    }

    /**
     * Test the property 'shopPlatform'
     */
    @Test
    public void shopPlatformTest() {
        // TODO: test shopPlatform
    }

    /**
     * Test the property 'shopCurrency'
     */
    @Test
    public void shopCurrencyTest() {
        // TODO: test shopCurrency
    }

    /**
     * Test the property 'shopName'
     */
    @Test
    public void shopNameTest() {
        // TODO: test shopName
    }

    /**
     * Test the property 'contactName'
     */
    @Test
    public void contactNameTest() {
        // TODO: test contactName
    }

    /**
     * Test the property 'contactEmail'
     */
    @Test
    public void contactEmailTest() {
        // TODO: test contactEmail
    }

    /**
     * Test the property 'contactPhoneNumber'
     */
    @Test
    public void contactPhoneNumberTest() {
        // TODO: test contactPhoneNumber
    }

    /**
     * Test the property 'seelServices'
     */
    @Test
    public void seelServicesTest() {
        // TODO: test seelServices
    }

}
