/*
 * Seel API
 * Seel API
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for OrderCreateNewOrderRequestSeelServicesInner
 */
public class OrderCreateNewOrderRequestSeelServicesInnerTest {
    private final OrderCreateNewOrderRequestSeelServicesInner model = new OrderCreateNewOrderRequestSeelServicesInner();

    /**
     * Model tests for OrderCreateNewOrderRequestSeelServicesInner
     */
    @Test
    public void testOrderCreateNewOrderRequestSeelServicesInner() {
        // TODO: test OrderCreateNewOrderRequestSeelServicesInner
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'price'
     */
    @Test
    public void priceTest() {
        // TODO: test price
    }

    /**
     * Test the property 'quoteId'
     */
    @Test
    public void quoteIdTest() {
        // TODO: test quoteId
    }

    /**
     * Test the property 'extraInfo'
     */
    @Test
    public void extraInfoTest() {
        // TODO: test extraInfo
    }

}
