/*
 * Seel API
 * Seel API
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.Address;
import com.konfigthis.client.model.Customer;
import com.konfigthis.client.model.Fulfillment;
import com.konfigthis.client.model.Item;
import com.konfigthis.client.model.OrderRefund;
import com.konfigthis.client.model.SeelService;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Order
 */
public class OrderTest {
    private final Order model = new Order();

    /**
     * Model tests for Order
     */
    @Test
    public void testOrder() {
        // TODO: test Order
    }

    /**
     * Test the property 'orderId'
     */
    @Test
    public void orderIdTest() {
        // TODO: test orderId
    }

    /**
     * Test the property 'orderNumber'
     */
    @Test
    public void orderNumberTest() {
        // TODO: test orderNumber
    }

    /**
     * Test the property 'cartId'
     */
    @Test
    public void cartIdTest() {
        // TODO: test cartId
    }

    /**
     * Test the property 'merchantId'
     */
    @Test
    public void merchantIdTest() {
        // TODO: test merchantId
    }

    /**
     * Test the property 'sessionId'
     */
    @Test
    public void sessionIdTest() {
        // TODO: test sessionId
    }

    /**
     * Test the property 'deviceId'
     */
    @Test
    public void deviceIdTest() {
        // TODO: test deviceId
    }

    /**
     * Test the property 'clientIp'
     */
    @Test
    public void clientIpTest() {
        // TODO: test clientIp
    }

    /**
     * Test the property 'createdTs'
     */
    @Test
    public void createdTsTest() {
        // TODO: test createdTs
    }

    /**
     * Test the property 'cancelledTs'
     */
    @Test
    public void cancelledTsTest() {
        // TODO: test cancelledTs
    }

    /**
     * Test the property 'updatedTs'
     */
    @Test
    public void updatedTsTest() {
        // TODO: test updatedTs
    }

    /**
     * Test the property 'lineItems'
     */
    @Test
    public void lineItemsTest() {
        // TODO: test lineItems
    }

    /**
     * Test the property 'shippingAddress'
     */
    @Test
    public void shippingAddressTest() {
        // TODO: test shippingAddress
    }

    /**
     * Test the property 'fulfillments'
     */
    @Test
    public void fulfillmentsTest() {
        // TODO: test fulfillments
    }

    /**
     * Test the property 'seelServices'
     */
    @Test
    public void seelServicesTest() {
        // TODO: test seelServices
    }

    /**
     * Test the property 'refunds'
     */
    @Test
    public void refundsTest() {
        // TODO: test refunds
    }

    /**
     * Test the property 'customer'
     */
    @Test
    public void customerTest() {
        // TODO: test customer
    }

    /**
     * Test the property 'extraInfo'
     */
    @Test
    public void extraInfoTest() {
        // TODO: test extraInfo
    }

}
