/*
 * Seel API
 * Seel API
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ProductUpdateProductDetailsRequestWeight
 */
public class ProductUpdateProductDetailsRequestWeightTest {
    private final ProductUpdateProductDetailsRequestWeight model = new ProductUpdateProductDetailsRequestWeight();

    /**
     * Model tests for ProductUpdateProductDetailsRequestWeight
     */
    @Test
    public void testProductUpdateProductDetailsRequestWeight() {
        // TODO: test ProductUpdateProductDetailsRequestWeight
    }

    /**
     * Test the property 'value'
     */
    @Test
    public void valueTest() {
        // TODO: test value
    }

    /**
     * Test the property 'unit'
     */
    @Test
    public void unitTest() {
        // TODO: test unit
    }

}
