/*
 * Seel API
 * Seel API
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.ProductDimensions;
import com.konfigthis.client.model.ProductEnabledServicesInner;
import com.konfigthis.client.model.ProductIdentifiers;
import com.konfigthis.client.model.ProductManufacturerWarranty;
import com.konfigthis.client.model.ProductProductAttributes;
import com.konfigthis.client.model.ProductWeight;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.net.URI;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Product
 */
public class ProductTest {
    private final Product model = new Product();

    /**
     * Model tests for Product
     */
    @Test
    public void testProduct() {
        // TODO: test Product
    }

    /**
     * Test the property 'merchantId'
     */
    @Test
    public void merchantIdTest() {
        // TODO: test merchantId
    }

    /**
     * Test the property 'variantId'
     */
    @Test
    public void variantIdTest() {
        // TODO: test variantId
    }

    /**
     * Test the property 'productId'
     */
    @Test
    public void productIdTest() {
        // TODO: test productId
    }

    /**
     * Test the property 'productTitle'
     */
    @Test
    public void productTitleTest() {
        // TODO: test productTitle
    }

    /**
     * Test the property 'variantTitle'
     */
    @Test
    public void variantTitleTest() {
        // TODO: test variantTitle
    }

    /**
     * Test the property 'brandName'
     */
    @Test
    public void brandNameTest() {
        // TODO: test brandName
    }

    /**
     * Test the property 'manufacturer'
     */
    @Test
    public void manufacturerTest() {
        // TODO: test manufacturer
    }

    /**
     * Test the property 'category1'
     */
    @Test
    public void category1Test() {
        // TODO: test category1
    }

    /**
     * Test the property 'category2'
     */
    @Test
    public void category2Test() {
        // TODO: test category2
    }

    /**
     * Test the property 'category3'
     */
    @Test
    public void category3Test() {
        // TODO: test category3
    }

    /**
     * Test the property 'category4'
     */
    @Test
    public void category4Test() {
        // TODO: test category4
    }

    /**
     * Test the property 'productDescription'
     */
    @Test
    public void productDescriptionTest() {
        // TODO: test productDescription
    }

    /**
     * Test the property 'imageUrl'
     */
    @Test
    public void imageUrlTest() {
        // TODO: test imageUrl
    }

    /**
     * Test the property 'price'
     */
    @Test
    public void priceTest() {
        // TODO: test price
    }

    /**
     * Test the property 'currency'
     */
    @Test
    public void currencyTest() {
        // TODO: test currency
    }

    /**
     * Test the property 'requiresShipping'
     */
    @Test
    public void requiresShippingTest() {
        // TODO: test requiresShipping
    }

    /**
     * Test the property 'modelNumber'
     */
    @Test
    public void modelNumberTest() {
        // TODO: test modelNumber
    }

    /**
     * Test the property 'condition'
     */
    @Test
    public void conditionTest() {
        // TODO: test condition
    }

    /**
     * Test the property 'sku'
     */
    @Test
    public void skuTest() {
        // TODO: test sku
    }

    /**
     * Test the property 'identifiers'
     */
    @Test
    public void identifiersTest() {
        // TODO: test identifiers
    }

    /**
     * Test the property 'manufacturerWarranty'
     */
    @Test
    public void manufacturerWarrantyTest() {
        // TODO: test manufacturerWarranty
    }

    /**
     * Test the property 'dimensions'
     */
    @Test
    public void dimensionsTest() {
        // TODO: test dimensions
    }

    /**
     * Test the property 'weight'
     */
    @Test
    public void weightTest() {
        // TODO: test weight
    }

    /**
     * Test the property 'productAttributes'
     */
    @Test
    public void productAttributesTest() {
        // TODO: test productAttributes
    }

    /**
     * Test the property 'createdTs'
     */
    @Test
    public void createdTsTest() {
        // TODO: test createdTs
    }

    /**
     * Test the property 'updatedTs'
     */
    @Test
    public void updatedTsTest() {
        // TODO: test updatedTs
    }

    /**
     * Test the property 'enabledServices'
     */
    @Test
    public void enabledServicesTest() {
        // TODO: test enabledServices
    }

}
