/*
 * Seel API
 * Seel API
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.net.URI;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ProductAddNewProductRequestManufacturerWarranty
 */
public class ProductAddNewProductRequestManufacturerWarrantyTest {
    private final ProductAddNewProductRequestManufacturerWarranty model = new ProductAddNewProductRequestManufacturerWarranty();

    /**
     * Model tests for ProductAddNewProductRequestManufacturerWarranty
     */
    @Test
    public void testProductAddNewProductRequestManufacturerWarranty() {
        // TODO: test ProductAddNewProductRequestManufacturerWarranty
    }

    /**
     * Test the property 'url'
     */
    @Test
    public void urlTest() {
        // TODO: test url
    }

    /**
     * Test the property 'termLength'
     */
    @Test
    public void termLengthTest() {
        // TODO: test termLength
    }

}
