/*
 * Seel API
 * Seel API
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.net.URI;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ProductPlan
 */
public class ProductPlanTest {
    private final ProductPlan model = new ProductPlan();

    /**
     * Model tests for ProductPlan
     */
    @Test
    public void testProductPlan() {
        // TODO: test ProductPlan
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'price'
     */
    @Test
    public void priceTest() {
        // TODO: test price
    }

    /**
     * Test the property 'currency'
     */
    @Test
    public void currencyTest() {
        // TODO: test currency
    }

    /**
     * Test the property 'imageUrl'
     */
    @Test
    public void imageUrlTest() {
        // TODO: test imageUrl
    }

    /**
     * Test the property 'url'
     */
    @Test
    public void urlTest() {
        // TODO: test url
    }

    /**
     * Test the property 'termLength'
     */
    @Test
    public void termLengthTest() {
        // TODO: test termLength
    }

    /**
     * Test the property 'coverageStarts'
     */
    @Test
    public void coverageStartsTest() {
        // TODO: test coverageStarts
    }

    /**
     * Test the property 'coverageIncludes'
     */
    @Test
    public void coverageIncludesTest() {
        // TODO: test coverageIncludes
    }

    /**
     * Test the property 'serviceType'
     */
    @Test
    public void serviceTypeTest() {
        // TODO: test serviceType
    }

    /**
     * Test the property 'replacementType'
     */
    @Test
    public void replacementTypeTest() {
        // TODO: test replacementType
    }

    /**
     * Test the property 'deductible'
     */
    @Test
    public void deductibleTest() {
        // TODO: test deductible
    }

}
