/*
 * Seel API
 * Seel API
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ProductEnabledServicesInner
 */
public class ProductEnabledServicesInnerTest {
    private final ProductEnabledServicesInner model = new ProductEnabledServicesInner();

    /**
     * Model tests for ProductEnabledServicesInner
     */
    @Test
    public void testProductEnabledServicesInner() {
        // TODO: test ProductEnabledServicesInner
    }

    /**
     * Test the property 'serviceType'
     */
    @Test
    public void serviceTypeTest() {
        // TODO: test serviceType
    }

    /**
     * Test the property 'isEnabled'
     */
    @Test
    public void isEnabledTest() {
        // TODO: test isEnabled
    }

    /**
     * Test the property 'createdTs'
     */
    @Test
    public void createdTsTest() {
        // TODO: test createdTs
    }

    /**
     * Test the property 'updatedTs'
     */
    @Test
    public void updatedTsTest() {
        // TODO: test updatedTs
    }

}
