/*
 * Seel API
 * Seel API
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ProductUpdateProductDetailsRequestIdentifiers
 */
public class ProductUpdateProductDetailsRequestIdentifiersTest {
    private final ProductUpdateProductDetailsRequestIdentifiers model = new ProductUpdateProductDetailsRequestIdentifiers();

    /**
     * Model tests for ProductUpdateProductDetailsRequestIdentifiers
     */
    @Test
    public void testProductUpdateProductDetailsRequestIdentifiers() {
        // TODO: test ProductUpdateProductDetailsRequestIdentifiers
    }

    /**
     * Test the property 'serialNumber'
     */
    @Test
    public void serialNumberTest() {
        // TODO: test serialNumber
    }

    /**
     * Test the property 'gtin'
     */
    @Test
    public void gtinTest() {
        // TODO: test gtin
    }

    /**
     * Test the property 'upc'
     */
    @Test
    public void upcTest() {
        // TODO: test upc
    }

    /**
     * Test the property 'isbn'
     */
    @Test
    public void isbnTest() {
        // TODO: test isbn
    }

    /**
     * Test the property 'barcode'
     */
    @Test
    public void barcodeTest() {
        // TODO: test barcode
    }

}
