/*
 * Seel API
 * Seel API
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.Fulfillment;
import com.konfigthis.client.model.FulfillmentLineItemsInner;
import com.konfigthis.client.model.FulfillmentListFulfillmentsResponse;
import com.konfigthis.client.model.FulfillmentUpdateFulfillmentDetailsRequest;
import com.konfigthis.client.model.FulfillmentUpdateFulfillmentDetailsRequestLineItemsInner;
import java.time.OffsetDateTime;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for FulfillmentApi
 */
@Disabled
public class FulfillmentApiTest {

    private static FulfillmentApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new FulfillmentApi(apiClient);
    }

    /**
     * Cancel a fulfillment
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void cancelFulfillmentTest() throws ApiException {
        String orderId = null;
        String fulfillmentId = null;
        String xSeelAPIKey = null;
        String xSeelAPIVersion = null;
        String partner = null;
        Fulfillment response = api.cancelFulfillment(orderId, fulfillmentId, xSeelAPIKey, xSeelAPIVersion, partner)
                .execute();
        // TODO: test validations
    }

    /**
     * Create a fulfillment
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createNewFulfillmentTest() throws ApiException {
        String fulfillmentId = null;
        OffsetDateTime createdTs = null;
        OffsetDateTime updatedTs = null;
        String trackingNumber = null;
        String carrier = null;
        String shipmentStatus = null;
        List<FulfillmentLineItemsInner> lineItems = null;
        String orderId = null;
        String xSeelAPIKey = null;
        String xSeelAPIVersion = null;
        String partner = null;
        String trackingUrl = null;
        Fulfillment response = api.createNewFulfillment(fulfillmentId, createdTs, updatedTs, trackingNumber, carrier, shipmentStatus, lineItems, orderId, xSeelAPIKey, xSeelAPIVersion, partner)
                .trackingUrl(trackingUrl)
                .execute();
        // TODO: test validations
    }

    /**
     * Get a fulfillment
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getDetailsTest() throws ApiException {
        String orderId = null;
        String fulfillmentId = null;
        String xSeelAPIKey = null;
        String xSeelAPIVersion = null;
        String partner = null;
        Fulfillment response = api.getDetails(orderId, fulfillmentId, xSeelAPIKey, xSeelAPIVersion, partner)
                .execute();
        // TODO: test validations
    }

    /**
     * List fulfillments
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listFulfillmentsTest() throws ApiException {
        String orderId = null;
        String xSeelAPIKey = null;
        String xSeelAPIVersion = null;
        String partner = null;
        Integer page = null;
        Integer pageSize = null;
        FulfillmentListFulfillmentsResponse response = api.listFulfillments(orderId, xSeelAPIKey, xSeelAPIVersion, partner)
                .page(page)
                .pageSize(pageSize)
                .execute();
        // TODO: test validations
    }

    /**
     * Update a fulfillment
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateFulfillmentDetailsTest() throws ApiException {
        OffsetDateTime updatedTs = null;
        String trackingNumber = null;
        String carrier = null;
        String shipmentStatus = null;
        List<FulfillmentUpdateFulfillmentDetailsRequestLineItemsInner> lineItems = null;
        String orderId = null;
        String fulfillmentId = null;
        String xSeelAPIKey = null;
        String xSeelAPIVersion = null;
        String partner = null;
        String trackingUrl = null;
        Fulfillment response = api.updateFulfillmentDetails(updatedTs, trackingNumber, carrier, shipmentStatus, lineItems, orderId, fulfillmentId, xSeelAPIKey, xSeelAPIVersion, partner)
                .trackingUrl(trackingUrl)
                .execute();
        // TODO: test validations
    }

}
