/*
 * Seel API
 * Seel API
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.Address;
import com.konfigthis.client.model.Customer;
import com.konfigthis.client.model.Item;
import com.konfigthis.client.model.Quote;
import com.konfigthis.client.model.QuoteGenerateQuoteRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for QuoteApi
 */
@Disabled
public class QuoteApiTest {

    private static QuoteApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new QuoteApi(apiClient);
    }

    /**
     * Create a quote
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void generateQuoteTest() throws ApiException {
        String sessionId = null;
        String type = null;
        List<Item> lineItems = null;
        Address shippingAddress = null;
        Customer customer = null;
        String partner = null;
        String xSeelAPIKey = null;
        String xSeelAPIVersion = null;
        String cartId = null;
        String merchantId = null;
        String deviceId = null;
        String clientIp = null;
        Object extraInfo = null;
        Quote response = api.generateQuote(sessionId, type, lineItems, shippingAddress, customer, partner, xSeelAPIKey, xSeelAPIVersion)
                .cartId(cartId)
                .merchantId(merchantId)
                .deviceId(deviceId)
                .clientIp(clientIp)
                .extraInfo(extraInfo)
                .execute();
        // TODO: test validations
    }

    /**
     * Get a quote
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getByIdTest() throws ApiException {
        String quoteId = null;
        String xSeelAPIKey = null;
        String xSeelAPIVersion = null;
        String partner = null;
        Quote response = api.getById(quoteId, xSeelAPIKey, xSeelAPIVersion, partner)
                .execute();
        // TODO: test validations
    }

}
